output: dist/
# releases:
#   - name: dev
#     jobs:
#       - name: release-dev-linux-deb
#         package:
#           platform: linux
#           target: deb
#           build_args:
#             enable-experiment: records

variables:
  # Your app information
  app_name: cookethflow
  app_version: 0.1.0
  build_name: 0.1.0
  build_number: '1'
  # Icon paths
  icon_path: assets/frame_271.png
  linux_icon_path: assets/frame_271.png

jobs:
  release-dev-linux-deb:
    name: Release Dev Linux DEB
    package:
      platform: linux
      targets: deb
    # Optional: Add signing configuration if needed
    # sign:
    #   enable: true
    #   key: path/to/key
    #   cert: path/to/cert
    #   password: yourpassword