icon: assets/frame_271.png
summary: A visual thinking tool.
group: Application/Emulator
vendor: Cooketh Company
packager:   Subroto Banerjee
packagerEmail: subroto.2003@gmail.com
license: MIT
url: https://github.com/CookethOrg/Cooketh-Flow

display_name: Cooketh Flow

keywords:
  - CookethOrg
  - Cooketh
  - cookethflow
  - Test
  - Application

generic_name: Visual Thinking Tool

categories:
  - Desktop
  - Flutter

startup_notify: true
# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml