display_name: Cooketh Flow
package_name: cookethflow
version: 0.1.0
architecture: x86_64

icon: assets/frame_271.png

keywords:
  - Cooketh
  - Flow
  - Visual Thinking
  - Productivity

generic_name: Visual Thinking Tool

categories:
  - Utility

startup_notify: true

# Library configuration
library_paths:
  - /usr/lib/x86_64-linux-gnu/
  - /lib/x86_64-linux-gnu/
  - /home/teewrath/Music/glib_extracted/usr/lib/x86_64-linux-gnu/  # Add extracted paths here
  - /home/teewrath/Music/atspi_extracted/usr/lib/x86_64-linux-gnu/
  - /home/teewrath/Music/libffi6_extracted/usr/lib/x86_64-linux-gnu/

# Required libraries (simplified)
include:
  - libglib-2.0.so.0
  - libgobject-2.0.so.0
  - libffi.so.6
  - libffi.so.8
  - libgcc_s.so.1
  - libstdc++.so.6
  - libatspi.so.0
  - libatk-1.0.so.0

# AppImage specific settings
appimage:
  additional_libs:
    - /home/teewrath/Music/glib_extracted/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
    - /home/teewrath/Music/glib_extracted/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    - /home/teewrath/Music/libffi6_extracted/usr/lib/x86_64-linux-gnu/libffi.so.6
    - /usr/lib/x86_64-linux-gnu/libffi.so.8
    - /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
    - /home/teewrath/Music/atspi_extracted/usr/lib/x86_64-linux-gnu/libatspi.so.0

  env:
    LD_LIBRARY_PATH: "$APPDIR/usr/lib"
    G_DEBUG: "fatal-warnings"

  exclude:
    - "*.a"
    - "*.la"
    - "*.dev"
    - "*.debug"
    - "/usr/include/*"