display_name: Cooketh Flow

icon: assets/frame_271.png

keywords:
  - Cooketh
  - Flow
  - CookethOrg
  - Flutter
  - Visual Thinking
  - Productivity

generic_name: Visual Thinking Tool

actions:
  - name: Say Hi
    label: say-hi
    arguments:
      - --say
      - hi
  - name: Say Bye
    label: say-bye
    arguments:
      - --say
      - bye

categories:
  - Utility

startup_notify: true

# Only include runtime libraries (not development packages)
include:
  - libglib-2.0.so.0
  - libgobject-2.0.so.0
  - libstdc++.so.6
  - libgcc_s.so.1

# Optional: Specify library paths if they're in non-standard locations
library_paths:
  - /usr/lib/x86_64-linux-gnu/
  - /lib/x86_64-linux-gnu/

# AppImage specific settings
appimage:
  # Exclude development files that might cause packaging errors
  exclude:
    - "*.a"
    - "*.la"
    - "*.dev"
    - "*.debug"
    - "/usr/share/doc/*"
    - "/usr/include/*"
  
  # Include essential GTK libraries for Flutter Linux apps
  additional_libs:
    - libgtk-3.so.0
    - libgdk-3.so.0
    - libpangocairo-1.0.so.0
    - libepoxy.so.0