display_name: Cooketh Flow
package_name: cookethflow
version: 0.1.0
architecture: amd64

maintainer:
  name: Subroto Banerjee
  email: subroto.2003@gmail.com

authors: "Subroto Banerjee <subroto.2003@gmail.com>, Antara Paul <paul.antara04@gmail.com>"

priority: optional
section: x11
installed_size: 15700

depends:
  - libglib2.0-0
  - libgtk-3-0
  - libc6
  - libstdc++6
  - libgcc-s1

# Changed from string to boolean
essential: false

icon: assets/frame_271.png

postinstall_script: |
  echo "Installed Cooketh Flow"
  update-desktop-database -q || true
  gtk-update-icon-cache -qtf /usr/share/icons/hicolor || true

postuninstall_script: |
  echo "You going? Whyyy ?"
  update-desktop-database -q || true
  gtk-update-icon-cache -qtf /usr/share/icons/hicolor || true

keywords:
  - Cooketh
  - Flow
  - Visual Thinking
  - Productivity

generic_name: Visual Thinking Application

categories:
  - Office
  - FlowChart

# Changed from string to boolean
startup_notify: true

startup_wm_class: cookethflow

desktop_entry:
  Exec: cookethflow
  Icon: cookethflow
  Type: Application
  Categories: Office;FlowChart;
  Terminal: false