# name: Build Windows EXE

# on: [push, workflow_dispatch]

# jobs:
#   build-windows:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
      
#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable
#           cache: true

#       - name: Install dependencies
#         run: flutter pub get

#       - name: Build Windows EXE
#         env:
#           SUPABASE_URL: ${{ vars.SUPABASE_URL }}
#           SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
#         run: flutter build windows --release
      
#       - name: Activate Fastforge
#         run: dart pub global activate fastforge
      
#       - name: Package using Fastforge
#         run: fastforge package --platform windows --targets exe

#       - name: Upload Artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: WindowsExecutable
#           path: dist/0.1.0/cookethflow-0.1.0-windows-setup.exe
#           retention-days: 7