name: Build Linux

on: [push, workflow_dispatch]

jobs:
  build-linux:
    runs-on: linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          type .env  # For debugging (optional)

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release
      
      - name: Package using Fastforge
        run: fastforge package --platform windows --targets exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsExecutable
          path: dist\0.1.0\cookethflow-0.1.0-windows-setup.exe
          retention-days: 7  # Optional: Set artifact retention period