name: Build Windows EXE

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    environment: .env
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create .env file and display values
        run: |
          # Define variables manually, handling potential secret masking
          $SUPABASE_URL = "${{ vars.SUPABASE_URL }}"
          if (-not $SUPABASE_URL) { $SUPABASE_URL = "default_url" }  # Fallback for debugging
          
          $SUPABASE_KEY = "${{ vars.SUPABASE_KEY }}"
          if (-not $SUPABASE_KEY) { $SUPABASE_KEY = "default_key" }  # Fallback for debugging
          
          # Write to .env file
          Add-Content -Path .env -Value "SUPABASE_URL=$SUPABASE_URL"
          Add-Content -Path .env -Value "SUPABASE_KEY=$SUPABASE_KEY"
          
          # Display values in logs
          Write-Output "Debug: SUPABASE_URL is $SUPABASE_URL"
          Write-Output "Debug: SUPABASE_KEY is $SUPABASE_KEY"
          
          # Show .env file contents
          type .env

      # Uncomment and adjust the remaining steps as needed
      # - name: Setup Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: stable
      #     cache: true

      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Build Windows EXE
      #   run: flutter build windows --release
      
      # - name: Activate Fastforge
      #   run: dart pub global activate fastforge
      
      # - name: Package using Fastforge
      #   run: fastforge package --platform windows --targets exe

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: WindowsExecutable
      #     path: dist/0.1.0/cookethflow-0.1.0-windows-setup.exe
      #     retention-days: 7