name: Build Windows EXE

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    environment: .env
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create .env file and display values
        run: |
          # Define variables manually for debugging (replace with actual values)
          $SUPABASE_URL = "${{ vars.SUPABASE_URL }}"
          $SUPABASE_KEY = "${{ vars.SUPABASE_KEY }}"
          
          # Write to .env file
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> .env
          
          # Display values in logs (bypassing secret masking)
          Write-Output "Debug: SUPABASE_URL is $SUPABASE_URL"
          Write-Output "Debug: SUPABASE_KEY is $SUPABASE_KEY"
          
          # Show .env file contents
          type .env

      # Uncomment and adjust the remaining steps as needed
      # - name: Setup Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: stable
      #     cache: true

      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Build Windows EXE
      #   run: flutter build windows --release
      
      # - name: Activate Fastforge
      #   run: dart pub global activate fastforge
      
      # - name: Package using Fastforge
      #   run: fastforge package --platform windows --targets exe

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: WindowsExecutable
      #     path: dist/0.1.0/cookethflow-0.1.0-windows-setup.exe
      #     retention-days: 7