name: Linux Multi-Distro Build

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - distro: ubuntu22.04
            arch: x86_64
          - distro: ubuntu20.04
            arch: x86_64
          - distro: debian-bookworm
            arch: x86_64
          - distro: fedora-latest
            arch: x86_64
          - distro: alpine-latest
            arch: x86_64
          - distro: centos-stream
            arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build on ${{ matrix.distro }} (${{ matrix.arch }})
        uses: uraimo/run-on-arch-action@v3
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}
          githubToken: ${{ github.token }}
          setup: |
            sudo apt-get update || true
            sudo yum check-update || true
            sudo apk update || true
            
          run: |
            # Install build dependencies
            if [ -f /etc/debian_version ]; then
              sudo apt-get install -y build-essential
            elif [ -f /etc/redhat-release ]; then
              sudo yum install -y gcc-c++ make
            elif [ -f /etc/alpine-release ]; then
              sudo apk add build-base
            fi
            
            # Your build commands here
            mkdir build
            cd build
            cmake ..
            make -j$(nproc)
